const ADDSURVEY = "ADDSURVEY";
const ADDTITLE = "ADDTITLE";
const ADDPRICE = "ADDPRICE";
const ADDSETTINGS = "ADDSETTINGS";
const SUBMITSURVEYTOBACKEND = "postsurveytobackend";

const SUBMITSURVEYTOBACKENDSUCCESS = "SUBMITSURVEYTOBACKENDSUCCESS";
const SUBMITSURVEYTOBACKENDERROR = "SUBMITSURVEYTOBACKENDERROR";

export {
  ADDSURVEY,
  ADDTITLE,
  ADDPRICE,
  ADDSETTINGS,
  SUBMITSURVEYTOBACKEND,
  SUBMITSURVEYTOBACKENDSUCCESS,
  SUBMITSURVEYTOBACKENDERROR,
};
