const ADDSURVEY = "ADDSURVEY";
const ADDTITLE = "ADDTITLE";
const ADDPRICE = "ADDPRICE";
const ADDSETTINGS = "ADDSETTINGS";
const SUBMITSURVEYTOBACKEND = "postsurveytobackend";

const SUBMITSURVEYTOBACKENDSUCCESS = "SUBMITSURVEYTOBACKENDSUCCESS";
const SUBMITSURVEYTOBACKENDERROR = "SUBMITSURVEYTOBACKENDERROR";


const FETCHSURVEYFROMBACKEND = 'FETCHSURVEYFROMBACKEND'
const FETCHSURVEYFROMBACKENDSUCCESS = 'FETCHSURVEYFROMBACKENDSUCCESS'

const FETCHINGMAPLOCATIONANDADDRESS = 'FETCHINGMAPLOCATIONANDADDRESS'
const FETCHINGLOCATION = 'FETCHINGLOCATION'

export {
  ADDSURVEY,
  ADDTITLE,
  ADDPRICE,
  ADDSETTINGS,
  SUBMITSURVEYTOBACKEND,
  SUBMITSURVEYTOBACKENDSUCCESS,
  SUBMITSURVEYTOBACKENDERROR,
  FETCHSURVEYFROMBACKEND,
  FETCHSURVEYFROMBACKENDSUCCESS,
  FETCHINGMAPLOCATIONANDADDRESS,
  FETCHINGLOCATION
};
