const FETCHCAMPAIGNS = "FETCHCAMPAIGNS";
const FETCHCAMPAIGNSSUCCESS = "FETCHCAMPAIGNSSUCCESS";
const POSTUPDATECAMPAIGNSTATUSTOBACKEND = "POSTUPDATECAMPAIGNSTATUSTOBACKEND";
const POSTUPDATECAMPAIGNSSTATUSTOBACKEND = "POSTUPDATECAMPAIGNSTATUSTOBACKEND";

export {
  FETCHCAMPAIGNS,
  FETCHCAMPAIGNSSUCCESS,
  POSTUPDATECAMPAIGNSTATUSTOBACKEND,
  POSTUPDATECAMPAIGNSSTATUSTOBACKEND,
};
